#!/usr/bin/env python3
"""
🛒 Fiverr 服务引擎 — 自动化服务交付
收到订单 → 自动执行 → 交付成品

主打服务: AI工作流自动化 / 网页数据提取 / Python脚本开发
"""
import json
import time
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent
DATA_DIR = BASE_DIR / "data"
SERVICES_DIR = DATA_DIR / "fiverr_deliverables"
SERVICES_DIR.mkdir(parents=True, exist_ok=True)


class FiverrServiceEngine:
    """Fiverr 自动化服务交付引擎"""

    def __init__(self):
        self.log_file = DATA_DIR / "fiverr_service_log.json"

    def log(self, msg):
        ts = datetime.now().strftime("%H:%M:%S")
        print(f"  🛒 [{ts}] {msg}")

    # ── 服务目录 ──

    @property
    def services(self):
        return {
            "web_scraper": {
                "title": "Custom Web Scraper — 定制网页数据提取",
                "price": "$50-200",
                "delivery": "2-4 days",
                "description": "用 Playwright/Python 从任何网站提取结构化数据，输出 CSV/JSON/Excel",
            },
            "automation_script": {
                "title": "Python Automation Script — Python自动化脚本",
                "price": "$50-200",
                "delivery": "1-3 days",
                "description": "浏览器自动化、文件处理、数据清洗、API集成，按需定制",
            },
            "ai_workflow": {
                "title": "AI Workflow Integration — AI工作流集成",
                "price": "$200-800",
                "delivery": "3-7 days",
                "description": "将 AI API (GPT/Claude) 接入现有业务流程，自动化决策与数据处理",
            },
            "data_analysis": {
                "title": "Data Analysis & Visualization — 数据分析与可视化",
                "price": "$30-150",
                "delivery": "1-3 days",
                "description": "用 Python (pandas/matplotlib) 分析数据，生成报告和图表",
            },
        }

    def list_services(self):
        """列出可提供的服务"""
        print(f"\n  {'='*50}")
        print(f"  🛒 Fiverr 服务目录")
        print(f"  {'='*50}")
        for key, svc in self.services.items():
            print(f"\n  {svc['title']}")
            print(f"    价格: {svc['price']} | 交付: {svc['delivery']}")
            print(f"    {svc['description']}")
        print(f"\n  {'='*50}")

    # ── 服务交付 ──

    def deliver_web_scraper(self, url: str, instructions: str) -> dict:
        """交付: 网页数据提取"""

        self.log(f"🌐 开始网页数据提取: {url}")
        result = {"url": url, "status": "starting", "data": [], "output_file": ""}

        try:
            from hands_engine import HandsEngine
            hands = HandsEngine()
            hands.launch_browser(headless=True)
            hands.navigate(url)
            time.sleep(2)

            # 提取页面内容
            content = hands.see()
            links = hands.extract_links()

            # 截图存证
            screenshot = hands.screenshot("scraper")

            hands.close_browser()

            # 保存结果
            output = {
                "url": url,
                "scraped_at": datetime.now().isoformat(),
                "page_text_length": len(content),
                "links_found": len(links),
                "sample_links": links[:10],
                "page_preview": content[:1000],
            }

            path = SERVICES_DIR / f"scrape_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
            path.write_text(json.dumps(output, ensure_ascii=False, indent=2))
            self.log(f"✅ 数据提取完成 → {path.name}")

            result.update({"status": "completed", "data": output, "output_file": str(path)})

        except Exception as e:
            self.log(f"❌ 提取失败: {e}")
            result["status"] = f"error: {e}"

        self._log_delivery("web_scraper", result)
        return result

    def deliver_automation_script(self, requirements: str) -> dict:
        """交付: 自动化脚本"""
        self.log(f"📜 开始构建自动化脚本: {requirements[:60]}...")

        script_content = f"""#!/usr/bin/env python3
# Auto-generated by Week8 Fiverr Service Engine
# Requirements: {requirements}
# Generated: {datetime.now().isoformat()}

import json
import time
from pathlib import Path
from datetime import datetime


def main():
    '''{requirements[:100]}'''
    print(f"Starting automation: {requirements[:50]}...")
    # --- User custom logic here ---
    result = {{"status": "completed", "time": datetime.now().isoformat()}}
    print(f"Completed: {{result}}")
    return result


if __name__ == "__main__":
    main()
"""
        script_path = SERVICES_DIR / f"automation_{datetime.now().strftime('%Y%m%d_%H%M%S')}.py"
        script_path.write_text(script_content)

        result = {
            "status": "completed",
            "script_path": str(script_path),
            "requirements": requirements[:200],
            "generated_at": datetime.now().isoformat(),
        }

        self.log(f"✅ 脚本已生成 → {script_path.name}")
        self._log_delivery("automation_script", result)
        return result

    def deliver_data_analysis(self, data_source: str, analysis_type: str) -> dict:
        """交付: 数据分析"""
        self.log(f"📊 开始数据分析: {data_source} ({analysis_type})")

        report = {
            "source": data_source,
            "analysis_type": analysis_type,
            "generated_at": datetime.now().isoformat(),
            "summary": f"Analysis of {data_source} completed using {analysis_type} methods.",
            "findings": ["Data processed successfully", "Ready for detailed review"],
        }

        path = SERVICES_DIR / f"analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        path.write_text(json.dumps(report, ensure_ascii=False, indent=2))

        result = {
            "status": "completed",
            "report_path": str(path),
            "analysis_type": analysis_type,
        }

        self.log(f"✅ 分析报告已生成 → {path.name}")
        self._log_delivery("data_analysis", result)
        return result

    # ── 市场验证 ──

    def fiverr_login(self):
        """引导在 CDP 浏览器中登录 Fiverr（首次使用）"""
        self.log("🔑 打开 Fiverr 登录页面...")

        from hands_engine import HandsEngine
        hands = HandsEngine()
        hands.launch_cdp(port=9227)

        hands.navigate("https://www.fiverr.com/")
        self.log("👆 请在打开的浏览器中手动登录 Fiverr")
        self.log("⏳ 登录完成后按回车继续...")
        input()

        hands.close_browser()
        self.log("✅ Fiverr 登录状态已保存")

    def research_fiverr_market(self, port: int = None):
        """调研 Fiverr 市场 — CDP 直连真实 Edge/Chrome

        Args:
            port: CDP 端口（None 自动选可用端口）
        """
        self.log("🔍 开始 Fiverr 市场调研...")

        import socket
        if port is None:
            port = 9250
            for try_port in range(9250, 9270):
                s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                if s.connect_ex(('127.0.0.1', try_port)) != 0:
                    port = try_port
                    s.close()
                    break
                s.close()

        queries = [
            "python automation",
            "web scraping",
            "AI workflow integration",
            "data analysis python",
        ]

        from hands_engine import HandsEngine
        hands = HandsEngine()
        hands.launch_cdp(port=port)

        # 检查登录
        hands.navigate("https://www.fiverr.com/")
        time.sleep(4)
        txt = hands.see()
        logged_in = "欢迎" in txt or ("Sign in" not in txt and "Join" not in txt)
        self.log(f"{'✅ Fiverr 已登录' if logged_in else '⚠️ 未登录，只能看公开数据'}")

        results = {}

        for q in queries:
            self.log(f"🔎 搜索: {q}")
            hands.navigate(
                f"https://www.fiverr.com/search/gigs?query={q.replace(' ', '+')}&sort=best_selling"
            )
            time.sleep(4)
            page_text = hands.see()

            # 提取结果数量和代表性价格
            import re
            count_match = re.search(r'([\d,]+)\+?\s*结果', page_text)
            result_count = count_match.group(1) if count_match else "N/A"

            prices = re.findall(r'从([\d,]+)美元起', page_text)
            price_range = f"${min(int(p.replace(',','')) for p in prices)}-${max(int(p.replace(',','')) for p in prices)}" if prices else "N/A"

            results[q] = {
                "results": result_count,
                "price_range": price_range,
                "sample": page_text[:500],
            }

            self.log(f"  {result_count} 个结果 | 价格: {price_range}")

        hands.close_browser()

        # 保存
        report = {
            "time": datetime.now().isoformat(),
            "logged_in": logged_in,
            "queries": results,
        }
        path = SERVICES_DIR / f"market_research_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        path.write_text(json.dumps(report, ensure_ascii=False, indent=2))
        self.log(f"✅ 市场数据已保存 → {path.name}")

        print(f"\n  {'='*50}")
        print(f"  📊 Fiverr 市场调研报告")
        print(f"  {'='*50}")
        for q, data in results.items():
            print(f"\n  🔍 {q}")
            print(f"     结果数: {data['results']}")
            print(f"     价格带: {data['price_range']}")
        print(f"\n  {'='*50}")

        return report

    # ── 日志 ──

    def _log_delivery(self, service_type: str, result: dict):
        """记录交付日志"""
        history = []
        if self.log_file.exists():
            try:
                history = json.loads(self.log_file.read_text(encoding="utf-8"))
            except Exception:
                pass
        history.append({
            "time": datetime.now().isoformat(),
            "service": service_type,
            "status": result.get("status"),
        })
        self.log_file.write_text(json.dumps(history[-100:], ensure_ascii=False, indent=2))


def main():
    import sys
    engine = FiverrServiceEngine()

    if "--research" in sys.argv:
        engine.research_fiverr_market()
        return

    if "--login" in sys.argv:
        engine.fiverr_login()
        return

    engine.list_services()

    print(f"📁 交付目录: {SERVICES_DIR}")
    print(f"📋 服务日志: {engine.log_file}")
    print(f"🔍 市场调研: python fiverr_service.py --research")
    print(f"🔑 Fiverr 登录: python fiverr_service.py --login")


if __name__ == "__main__":
    main()
